version: "3.9"  
services:
    proxyrev:        
        image: nginx
        hostname: proxyrev
        domainname: proxyrev
        container_name: proxyrev
    
        ports:
        - "80:80"
        - "443:443"
        volumes:
#        - ./nginx.conf:/etc/nginx/nginx.conf:ro 
        - ./default.conf:/etc/nginx/conf.d/default.conf    
        - ./example1.crt:/etc/nginx/conf.d/example1.crt        
        - ./example1.key:/etc/nginx/conf.d/example1.key                
        - ./htpasswd:/htpasswd
        
        networks:
          - app-tier  

    whoami:        
        image: containous/whoami
        hostname: whoami
        domainname: whoami
        container_name: whoami
 
        networks:
          - app-tier       
      
networks:
  app-tier:
    driver: bridge  